source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BXSlider_Example', :exclusive => true do
  pod "BXSlider", :path => "../"
end

target 'BXSlider_Tests', :exclusive => true do
  pod "BXSlider", :path => "../"

  
end
